<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="nb-philipps-7" name="com.perfectomobile.StcTest" tests="2" failures="2" timestamp="18 Feb 2015 01:39:02 GMT" time="57.983" errors="0">
  <testcase name="f" time="28.580" classname="com.perfectomobile.StcTest">
    <failure type="java.lang.RuntimeException" message="Failed to open device 219595A5">
      <![CDATA[java.lang.RuntimeException: Failed to open device 219595A5
	at com.perfectomobile.selenium.MobileDevice.open(MobileDevice.java:101)
	at com.perfectomobile.StcTest.testrun(StcTest.java:115)
	at com.perfectomobile.StcTest.f(StcTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.perfectomobile.httpclient.HttpClientException: Failed to execute command handset open : Cannot open device 219595A5 for user philipps@perfectomobile.com, device is in use.
	at com.perfectomobile.selenium.MobileEntity.processCommonResponse(MobileEntity.java:94)
	at com.perfectomobile.selenium.MobileDevice.processResponse(MobileDevice.java:504)
	at com.perfectomobile.selenium.MobileEntity.executeCommand(MobileEntity.java:58)
	at com.perfectomobile.selenium.MobileEntity.executeCommand(MobileEntity.java:50)
	at com.perfectomobile.selenium.MobileDevice.open(MobileDevice.java:99)
	... 22 more
]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="29.403" classname="com.perfectomobile.StcTest">
    <failure type="java.lang.RuntimeException" message="Failed to open device 1E674EB8">
      <![CDATA[java.lang.RuntimeException: Failed to open device 1E674EB8
	at com.perfectomobile.selenium.MobileDevice.open(MobileDevice.java:101)
	at com.perfectomobile.StcTest.testrun(StcTest.java:115)
	at com.perfectomobile.StcTest.f(StcTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.perfectomobile.httpclient.HttpClientException: Failed to execute command handset open : Cannot open device 1E674EB8 for user philipps@perfectomobile.com, device is in use.
	at com.perfectomobile.selenium.MobileEntity.processCommonResponse(MobileEntity.java:94)
	at com.perfectomobile.selenium.MobileDevice.processResponse(MobileDevice.java:504)
	at com.perfectomobile.selenium.MobileEntity.executeCommand(MobileEntity.java:58)
	at com.perfectomobile.selenium.MobileEntity.executeCommand(MobileEntity.java:50)
	at com.perfectomobile.selenium.MobileDevice.open(MobileDevice.java:99)
	... 22 more
]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- com.perfectomobile.StcTest -->
